import { TOPICS, score, counts } from './src/core.js';
import { attachSources, sourceStats } from './src/zhihu.js';
import { HISTORY_STORAGE_KEY, createReportRecord, readHistory, upsertHistory, removeHistory } from './src/history.js';

const asset = (name) => `./docs/assets/${name}`;
const state = { page: 'home', mode: 'exam', topic: TOPICS[0], answer: '', points: [], sources: [], guide: null, learningLoading: false, searchSource: 'zhihu-search', evaluationSource: 'zhihu-answer', before: 0, reteachText: '', selectedPoint: null, error: '', customMode: false, customDraft: '', reportId: '', historyRecord: null };
const app = document.querySelector('#app');

function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char])); }
function getHistory() { try { return readHistory(localStorage.getItem(HISTORY_STORAGE_KEY)); } catch { return []; } }
function writeHistory(records) { try { localStorage.setItem(HISTORY_STORAGE_KEY, JSON.stringify(records)); return true; } catch { return false; } }
function persistReport() { if (!state.points.length || state.reportId) return state.reportId; const record = createReportRecord({ topic: state.topic, mode: state.mode, answer: state.answer, before: state.before, points: state.points }); state.reportId = record.id; writeHistory(upsertHistory(getHistory(), record)); return record.id; }
function resetSession() { Object.assign(state, { page: 'home', answer: '', points: [], sources: [], guide: null, learningLoading: false, before: 0, error: '', customMode: false, customDraft: '', evaluationSource: 'zhihu-answer', reportId: '', historyRecord: null }); }
function shell(content) { app.innerHTML = `<div class="shell"><nav class="nav"><div class="brand"><span class="brand-mark">知</span>知乎 · 答主考官</div><button class="history" data-action="history">历史报告${getHistory().length ? ` <span class="history-count">${getHistory().length}</span>` : ''}</button></nav>${content}<div class="footer-note">高赞回答代表社区观点，不等于绝对事实 · 本轮使用知乎搜索与知乎直答</div></div>`; }
function mascot(stateName = 'thinking', text = '我只挑知识，不挑表达。') { return `<div class="mascot-card"><img class="mascot" src="${asset(stateName === 'thinking' ? 'liukanshan-thinking.gif' : 'liukanshan-front.jpg')}" alt="刘看山${stateName === 'thinking' ? '正在思考' : '考官'}" /><p>${text}</p></div>`; }
function home() { shell(`<main class="hero"><section><div class="eyebrow">主动回忆 · 社区校验 · 可见进步</div><h1>${state.mode === 'learn' ? '从 0 开始，<br/>知乎带你入门' : '你讲一遍，<br/>知乎来挑错'}</h1><p>${state.mode === 'learn' ? '先用知乎真实内容搭一张入门地图，再用自己的话复述，确认你真的理解了。' : '别急着看答案。先用自己的话解释一个问题，再由知乎社区观点与直答检验你的理解。'}</p>${mascot('thinking', state.mode === 'learn' ? '不知道也没关系，我们从第一步开始。' : '准备好了吗？')}</section><section class="panel topic-panel"><h2>选择一个主题</h2><div class="mode-switch"><button class="mode-card ${state.mode === 'exam' ? 'selected' : ''}" data-mode="exam"><strong>先讲再考</strong><small>适合已有一些了解的主题</small></button><button class="mode-card ${state.mode === 'learn' ? 'selected' : ''}" data-mode="learn"><strong>从 0 掌握</strong><small>先看入门地图，再用自己的话复述</small></button></div>${TOPICS.map((t) => `<button class="topic ${state.topic.id === t.id ? 'selected' : ''}" data-topic="${t.id}"><strong>${t.title}</strong><small>${t.tag} · ${t.description}</small></button>`).join('')}<button class="topic ${state.customMode || state.topic.id === 'custom' ? 'selected' : ''}" data-action="custom-open"><strong>＋ 自定义主题</strong><small>输入你正在学习的问题</small></button>${state.topic.id === 'custom' && !state.customMode ? `<div class="custom-selected"><strong>当前主题</strong><span>${state.topic.title}</span></div>` : ''}${state.customMode ? `<div class="custom-form"><label for="custom-topic">你的问题</label><input id="custom-topic" value="${state.customDraft.replace(/"/g, '&quot;')}" placeholder="例如：如何建立长期阅读习惯？" maxlength="80"/><div class="custom-form-actions"><button class="btn" data-action="custom-save">使用这个主题</button><button class="btn secondary" data-action="custom-cancel">取消</button></div><small>输入后点击“使用这个主题”，不会弹出系统对话框。</small>${state.error ? `<div class="error">${state.error}</div>` : ''}</div>` : ''}<div class="actions"><button class="btn" data-action="start">${state.mode === 'learn' ? '开始入门 →' : '开始考试 →'}</button></div></section></main>`); if (state.customMode) requestAnimationFrame(() => document.querySelector('#custom-topic')?.focus()); }
function statement() { shell(`<div class="topline"><div><div class="eyebrow">第 1 轮 / 2 轮</div><h1>${state.topic.title}</h1><div class="muted">先讲，再检索。建议 150～500 字。</div></div><div class="muted">考官正在记录评分点</div></div><div class="layout"><section class="panel" style="padding:24px"><textarea id="answer" class="answer" placeholder="用自己的话解释这个问题……\n\n可以从：你最先想到的结论、判断依据、适用条件开始。">${state.answer}</textarea>${state.error ? `<div class="error">${state.error}</div>` : ''}<div class="actions"><button class="btn" data-action="submit">提交我的讲述</button><button class="btn secondary" data-action="home">返回选题</button></div></section><aside class="panel side-card">${mascot('thinking','我正在找能证明这件事的回答。')}<ul class="prompt-list"><li>你认为最先被影响的工作是什么？</li><li>你判断的依据是什么？</li><li>哪些能力短期内仍然重要？</li></ul></aside></div>`); }
function learn() { if (state.learningLoading) { shell(`<section class="panel" style="padding:48px;text-align:center"><div class="eyebrow">正在检索知乎 · 正在生成入门地图</div><h1 style="font-size:32px">先把这个问题讲明白</h1><p class="muted">主题：${state.topic.title}</p><div class="progress" style="max-width:420px;margin:26px auto"><i style="width:68%"></i></div>${mascot('thinking','我先帮你找到最重要的概念。')}</section>`); return; } const guide = state.guide; if (!guide) { shell(`<section class="panel" style="padding:40px;text-align:center"><div class="eyebrow">从 0 掌握</div><h1 style="font-size:30px">入门地图还没准备好</h1><p class="error">${state.error || '知乎服务暂时不可用，请稍后重试。'}</p><div class="actions" style="justify-content:center"><button class="btn" data-action="start">重新获取</button><button class="btn secondary" data-action="home">返回选题</button></div></section>`); return; } shell(`<div class="topline"><div><div class="eyebrow">从 0 掌握 · 第 1 步 / 2 步</div><h1>${state.topic.title}</h1><div class="muted">先看入门地图，再用自己的话复述，不要求一次讲对。</div></div>${mascot('thinking','先理解，再证明自己会讲。')}</div><section class="panel guide-panel"><div class="eyebrow">知乎直答入门地图</div><p class="guide-overview">${guide.overview}</p><div class="guide-points">${guide.keyPoints.map((point, index) => `<article class="guide-point"><span>${index + 1}</span><div><h3>${point.title}</h3><p>${point.explanation}</p>${point.example ? `<small>例子：${point.example}</small>` : ''}</div></article>`).join('')}</div>${guide.misconceptions.length ? `<div class="guide-misconceptions"><strong>先避开这些误区</strong><ul>${guide.misconceptions.map((item) => `<li>${item}</li>`).join('')}</ul></div>` : ''}<div class="guide-sources"><strong>资料来源</strong>${state.sources.slice(0, 4).map((source) => `<a href="${source.url}" target="_blank" rel="noreferrer">${source.title} · ${source.author} ↗</a>`).join('')}</div></section><section class="panel learn-check"><div class="eyebrow">第 2 步 · 复述确认</div><h2>现在用自己的话说说看</h2><p class="muted">${guide.starterQuestion || '你认为这个问题最重要的三个概念是什么？'}</p><textarea id="learning-answer" class="answer" placeholder="我现在的理解是……">${state.answer}</textarea>${state.error ? `<div class="error">${state.error}</div>` : ''}<div class="actions"><button class="btn" data-action="learning-submit">提交我的理解</button><button class="btn secondary" data-action="home">换个主题</button></div></section>`); }
function researching() { shell(`<section class="panel" style="padding:48px;text-align:center"><div class="eyebrow">正在检索知乎 · 正在调用知乎直答</div><h1 style="font-size:32px">我正在找能证明这件事的回答</h1><p class="muted">主题：${state.topic.title}</p><div class="progress" style="max-width:420px;margin:26px auto"><i style="width:68%"></i></div>${mascot('thinking','先讲后搜，证据马上到。')}</section>`); }
function result() { const c = counts(state.points); const percent = score(state.points); const s = sourceStats(state.points); const sourceNote = `<div class="source-note">知乎直答已完成 ${s.matched} / ${s.total} 个知识点绑定相关搜索来源${s.fallback ? `，其余 ${s.fallback} 个保留直答综合说明` : ''}</div>`; shell(`<div class="topline"><div><div class="eyebrow">正在对照 ${state.points.length} 个关键点 · 已完成 ${state.points.length} / ${state.points.length}</div><h1>答主比对</h1><div class="muted">掌握度 <strong style="color:var(--blue);font-size:21px">${percent}%</strong>　<a href="#rules" style="color:var(--blue)">查看评分规则</a></div></div>${mascot('thinking','这里需要再解释一步。')}</div><div class="progress"><i style="width:100%"></i></div>${sourceNote}<div class="layout" style="margin-top:20px"><section class="results">${state.points.map(resultCard).join('')}</section><aside class="panel side-card"><h3>本轮概览</h3><p><span class="check">● ${c.accurate} 条准确覆盖</span></p><p style="color:var(--orange)">● ${c.correction} 处需要修正</p><p style="color:var(--orange)">● ${c.missing} 个关键遗漏</p><p style="color:var(--purple)">● ${c.difference} 个观点差异</p><button class="btn" data-action="report">查看掌握度报告</button></aside></div>`); }
function resultCard(p) { const labels = { accurate: '准确覆盖', correction: '需要修正', missing: '关键遗漏', difference: '观点差异' }; const live = p.sourceType === '真实搜索摘要'; const badge = live ? `<span class="source-badge live">真实搜索摘要 · 相关度 ${Math.round((p.sourceRelevance || 0) * 100)}%</span>` : `<span class="source-badge fallback">${p.sourceType || '未绑定来源'}</span>`; const sourceLink = p.url ? `<a href="${p.url}" target="_blank" rel="noreferrer">查看知乎原文 ↗</a>` : '<span class="muted">未返回可验证链接</span>'; return `<article class="card result-card ${p.status}"><div class="result-head"><div><span class="tag ${p.status}">${labels[p.status]}</span><h2 style="font-size:18px;margin:10px 0 0">${p.title}</h2></div>${p.status !== 'accurate' && p.prompt ? `<button class="btn secondary" data-reteach="${p.id}">我来补讲</button>` : ''}</div><div class="claim"><strong>你的讲述：</strong>${p.user}</div><p><strong>考官刘看山：</strong>${p.feedback}</p><div class="quote">“${p.quote}”<br/>${badge}</div><div class="source"><span>知乎来源：${p.sourceTitle} · 作者：${p.author}</span>${sourceLink}</div></article>`; }
function reteach() { const p = state.points.find((item) => item.id === state.selectedPoint); shell(`<div class="topline"><div><div class="eyebrow">第 2 轮 · 针对性补讲</div><h1>把这一点讲清楚</h1><div class="muted">待补讲：${p.title}</div></div>${mascot('front','我在听，请继续。')}</div><div class="layout"><aside class="panel side-card"><span class="tag ${p.status}">待补讲</span><h3>${p.title}</h3><div class="quote">${p.prompt}</div><p class="muted" style="font-size:13px">提示：不要复述原文，用你自己的话说明条件、原因或例子。</p></aside><section class="panel" style="padding:24px"><textarea id="reteach" class="answer" placeholder="我补充说明……">${state.reteachText}</textarea>${state.error ? `<div class="error">${state.error}</div>` : ''}<div class="actions"><button class="btn" data-action="rescore">提交补讲并复测</button><button class="btn secondary" data-action="results">暂时返回比对</button></div></section></div>`); }
function report() { persistReport(); const after = score(state.points); const c = counts(state.points); const generic = state.topic.id === 'ai-coder' ? 'AI 会优先改变规则清晰、可拆分的任务，但人的上下文判断、验证与责任仍不可替代。' : `围绕“${state.topic.title}”，可靠的理解需要同时覆盖结论、关键条件和适用边界。`; shell(`<section class="panel" style="padding:28px"><div class="eyebrow">本次练习完成 · 已保存到历史报告</div><div class="report-hero"><div class="score-ring" style="--score:${after * 3.6}deg"><strong>${after}%</strong></div><div><h1 style="margin:0 0 8px">你已经更接近真正理解</h1><p class="muted">补讲前 ${state.before}% → 补讲后 ${after}%</p><p>你已经覆盖了 ${c.accurate} 个关键点。下一步，继续验证观点差异背后的适用条件。</p></div></div><div class="stat-grid"><div class="stat"><b class="check">${c.accurate}</b>准确覆盖</div><div class="stat"><b style="color:var(--orange)">${c.correction}</b>需要修正</div><div class="stat"><b style="color:var(--orange)">${c.missing}</b>关键遗漏</div><div class="stat"><b style="color:var(--purple)">${c.difference}</b>观点差异</div></div></section><section class="panel knowledge"><div class="eyebrow">可复制知识卡片</div><h2>${state.topic.title}</h2><p><strong>一句话结论：</strong>${generic}</p><p><strong>我的最终理解：</strong>${state.answer || '我需要在补讲后重新组织自己的解释。'}</p><p class="muted" style="font-size:13px">来源列表：知乎搜索摘要与知乎直答综合说明已明确区分，AI 说明不替代原文。</p><div class="actions"><button class="btn" data-action="copy">复制知识卡片</button><button class="btn secondary" data-action="home">再考一次</button></div></section>`); }

function history() { const records = getHistory(); shell(`<div class="topline"><div><div class="eyebrow">学习档案</div><h1>历史报告</h1><div class="muted">报告保存在当前浏览器中，换设备或清理浏览器数据后不会同步。</div></div><button class="btn secondary" data-action="home">返回选题</button></div>${records.length ? `<section class="history-list">${records.map((record) => { const date = new Date(record.createdAt); const when = Number.isNaN(date.getTime()) ? '时间未知' : date.toLocaleString('zh-CN', { dateStyle: 'medium', timeStyle: 'short' }); return `<article class="panel history-item"><button class="history-open" data-history-id="${escapeHtml(record.id)}"><div><strong>${escapeHtml(record.topic.title)}</strong><small>${record.mode === 'learn' ? '从 0 掌握' : '先讲再考'} · ${escapeHtml(when)}</small></div><span class="history-score">${Number(record.after) || 0}%</span></button><button class="history-delete" data-delete-history="${escapeHtml(record.id)}" aria-label="删除这条历史报告">删除</button></article>`; }).join('')}</section><div class="history-actions"><button class="btn secondary" data-action="clear-history">清空历史报告</button></div>` : `<section class="panel empty-history"><h2>还没有历史报告</h2><p class="muted">完成一次练习并查看掌握度报告后，记录会自动保存在这里。</p><button class="btn" data-action="home">开始第一次练习</button></section>`}`); }

async function searchSources(query) { const response = await fetch('/api/search', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ query }) }); if (!response.ok) throw new Error('search failed'); return response.json(); }
async function evaluateWithZhihu(topic, answer) { const response = await fetch('/api/evaluate', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ topic, answer }) }); if (!response.ok) throw new Error('evaluation failed'); return response.json(); }
async function learnWithZhihu(topic) { const response = await fetch('/api/learn', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ topic }) }); if (!response.ok) throw new Error('learning guide failed'); return response.json(); }
async function reteachWithZhihu(topic, point, answer) { const response = await fetch('/api/reteach', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ topic, point, answer }) }); if (!response.ok) throw new Error('reteach failed'); return response.json(); }
async function loadLearningGuide() { state.learningLoading = true; state.error = ''; render(); const [searchResult, guideResult] = await Promise.allSettled([searchSources(state.topic.title), learnWithZhihu(state.topic.title)]); const search = searchResult.status === 'fulfilled' ? searchResult.value : null; const guide = guideResult.status === 'fulfilled' ? guideResult.value : null; state.learningLoading = false; if (!search || search.fallback || !Array.isArray(search.items) || !search.items.length) { state.error = search?.message || '知乎搜索没有返回可用结果，请稍后重试。'; render(); return; } if (!guide || guide.fallback || !guide.guide?.keyPoints?.length) { state.error = guide?.message || '知乎直答入门指南暂时不可用，请稍后重试。'; render(); return; } state.sources = search.items; state.searchSource = search.source || 'zhihu-search'; state.guide = guide.guide; render(); }
function render() { ({ home, statement, learn, result, reteach, report, history, researching }[state.page] || home)(); }

document.addEventListener('click', async (event) => {
  const el = event.target.closest('[data-action],[data-topic],[data-reteach],[data-mode],[data-history-id],[data-delete-history]'); if (!el) return;
  if (el.dataset.mode) { state.mode = el.dataset.mode; state.error = ''; render(); return; }
  if (el.dataset.topic) { state.topic = TOPICS.find((t) => t.id === el.dataset.topic); state.customMode = false; render(); return; }
  if (el.dataset.action === 'custom-open') { state.customMode = true; state.error = ''; render(); return; }
  if (el.dataset.action === 'custom-cancel') { state.customMode = false; state.customDraft = ''; render(); return; }
  if (el.dataset.action === 'custom-save') { const custom = document.querySelector('#custom-topic')?.value.trim() || ''; if (custom.length < 4) { state.error = '问题至少需要 4 个字，例如“如何建立长期阅读习惯？”'; render(); return; } state.topic = { id: 'custom', title: custom, tag: '自定义主题', description: '用自己的话解释，再由搜索结果帮助你校验。' }; state.customDraft = custom; state.customMode = false; state.error = ''; render(); return; }
  if (el.dataset.action === 'history') { state.page = 'history'; state.error = ''; render(); return; }
  if (el.dataset.historyId) { const record = getHistory().find((item) => item.id === el.dataset.historyId); if (!record) { state.error = '这条历史报告已不存在。'; render(); return; } Object.assign(state, { page: 'report', mode: record.mode || 'exam', topic: record.topic, answer: record.answer || '', points: record.points || [], before: Number(record.before) || 0, reportId: record.id, historyRecord: record, error: '' }); render(); return; }
  if (el.dataset.deleteHistory) { writeHistory(removeHistory(getHistory(), el.dataset.deleteHistory)); render(); return; }
  if (el.dataset.action === 'clear-history') { writeHistory([]); render(); return; }
  if (el.dataset.action === 'home') { resetSession(); render(); return; }
  if (el.dataset.action === 'start') { state.page = state.mode === 'learn' ? 'learn' : 'statement'; render(); if (state.mode === 'learn') loadLearningGuide(); return; }
  if (el.dataset.action === 'learning-submit') {
    const answer = document.querySelector('#learning-answer')?.value || ''; state.answer = answer;
    if (answer.trim().length < 30) { state.error = '至少输入 30 个字，用自己的话复述刚才的入门地图。'; render(); return; }
    state.page = 'researching'; state.error = ''; render();
    try {
      const direct = await evaluateWithZhihu(state.topic.title, answer);
      if (!direct || direct.fallback || !Array.isArray(direct.items) || direct.items.length < 3) throw new Error('知乎直答没有返回可用评估，请稍后重试。');
      state.evaluationSource = 'zhihu-answer'; state.points = attachSources(direct.items, state.sources, { topic: state.topic.title }); state.before = score(state.points); state.page = 'result'; render();
    } catch (error) { state.error = error.message || '知乎直答评估失败，请稍后重试。'; state.page = 'learn'; render(); }
    return;
  }
  if (el.dataset.action === 'submit') {
    const answer = document.querySelector('#answer')?.value || ''; state.answer = answer;
    if (answer.trim().length < 30) { state.error = '至少输入 30 个字，让考官有足够内容来判断。'; render(); return; }
    state.page = 'researching'; state.error = ''; render();
    const [searchResult, directResult] = await Promise.allSettled([searchSources(state.topic.title), evaluateWithZhihu(state.topic.title, answer)]);
    const search = searchResult.status === 'fulfilled' ? searchResult.value : null;
    const direct = directResult.status === 'fulfilled' ? directResult.value : null;
    if (!search || search.fallback || !Array.isArray(search.items) || !search.items.length) { state.error = search?.message || '知乎搜索没有返回可用结果，请稍后重试。'; state.page = 'statement'; render(); return; }
    if (!direct || direct.fallback || !Array.isArray(direct.items) || direct.items.length < 3) { state.error = direct?.message || '知乎直答没有返回可用评估，请稍后重试。'; state.page = 'statement'; render(); return; }
    state.sources = search.items; state.searchSource = search.source || 'zhihu-search'; state.evaluationSource = 'zhihu-answer';
    state.points = attachSources(direct.items, state.sources, { topic: state.topic.title });
    state.before = score(state.points); state.page = 'result'; render(); return;
  }
  if (el.dataset.reteach) { state.selectedPoint = el.dataset.reteach; state.reteachText = ''; state.error = ''; state.page = 'reteach'; render(); return; }
  if (el.dataset.action === 'results') { state.page = 'result'; state.error = ''; render(); return; }
  if (el.dataset.action === 'rescore') { const text = document.querySelector('#reteach')?.value || ''; if (text.trim().length < 15) { state.error = '请至少补充 15 个字，并尽量包含条件或原因。'; render(); return; } state.reteachText = text; state.page = 'researching'; state.error = ''; render(); try { const response = await reteachWithZhihu(state.topic.title, state.points.find((p) => p.id === state.selectedPoint), text); if (!response?.items?.length || response.fallback) throw new Error(response?.message || '知乎直答没有返回复测结果'); const updated = attachSources(response.items.slice(0, 1), state.sources, { topic: state.topic.title })[0]; state.points = state.points.map((p) => p.id === updated.id || p.id === state.selectedPoint ? { ...updated, id: p.id } : p); state.page = 'result'; render(); } catch (error) { state.error = error.message || '知乎直答复测失败，请稍后重试。'; state.page = 'reteach'; render(); } return; }
  if (el.dataset.action === 'report') { state.page = 'report'; render(); return; }
  if (el.dataset.action === 'copy') { const text = `${state.topic.title}\n一句话结论：${state.topic.id === 'ai-coder' ? 'AI 会优先改变规则清晰、可拆分的任务，但人的上下文判断、验证与责任仍不可替代。' : '可靠的理解需要同时覆盖结论、关键条件和适用边界。'}\n我的最终理解：${state.answer}`; try { await navigator.clipboard?.writeText(text); } catch { /* 剪贴板不可用时仍给出视觉反馈 */ } el.textContent = '已复制 ✓'; }
});
document.addEventListener('input', (event) => { if (event.target.id === 'answer') state.answer = event.target.value; if (event.target.id === 'reteach') state.reteachText = event.target.value; if (event.target.id === 'custom-topic') state.customDraft = event.target.value; });
render();
